services:
  - type: web
    name: my-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    redirects:
      - source: "/*"
        destination: "/"
        status: 200
